apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://my-app-otel-collector:4317"
  PAYMENT_SERVICE_URL: "http://my-app-payment-service:8000"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000"