apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "changeme"
  MYSQL_DATABASE: "quickcart"
  MYSQL_USER: "changeme_user"
  MYSQL_PASSWORD: "changeme"